travis:
  secure:
    BINSTAR_TOKEN: U6zBt9Jj5azFk3r2uWEtAPqhX2JEiQUV2wBwEKE8ZItzk3JlHQTPLkoLLzn3DWClBoeLMYsxsT6rG33EfhDiUOncv445cahvpGekHq9vzdQYp7TBy711Fq58F1pxtTlg9R7xJ48JVEy8mRARfWs+sJwb1qlhlAIBlcMPAFDDBvYcCOhVocZJUHrEsqDRkCxtkvkbUHJi9qCM7B9FkiB3g3Hb4VtzJcX6rhRGY9AYsbKYBrAJf12TYLJMVN6D9EXMPk7Wo/ji6+La9vJ9MpUzUghIwIe/5hMs/KAsao80H5BZ51bPJUirt603WefMPDX3rizEPKTdGNPU3MUX7cmGCoIOLHb8c15d0MW2T0TwViLYX3L8txSE2dsqeYW3XLkKZXCY+xXW8FP0Bxuy2be7nGEHrjJ+WTEbrBDaa6mM/hVNZ5nuUSrENCfdZAT2gyS3fuAfdwxoC8kYKF1xGtBo0516M0ip+FfauhsZ8f4tJPxFiufn3/cuHtNoT63oCBplyuREtr2MYj+EWickfJHpQBVKauBSur5sX3yGIJYXCjFdV86oTa6BSEh9UiVGRsQExl+nz21Ol/RpJNXvlChlJKJA91Jba3RAyqB/nD0PMEsztZ6YQG/pOZDdO0+o1DeZPnD6Q0sDzXky5V91IxRXBouM+bczMT9BM+MPGDpXYYg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
